name: "web_demo"
mode: "dev"
port: 8081

log:
  level: "debug"
  filename: "web_demo.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "abc123"
  dbname: "db1"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "192.168.238.128"
  port: 6379
#  db: 0